### ISSUE TITLE
Seit einigen Tagen keine Funktion mehr!!

### ISSUE THREAD

**Issue by martinkuck** [amiantos/pibar#47] opened 2022-12-29 10:45 UTC
Seit einigen Tagen keine Funktion mehr, (Test Connection = Success) Trotzden Offline.

**Comment by MC-1984** [comment] 2023-01-05 18:29
This is a duplicate of #46

**Comment by amiantos** [comment] 2023-01-05 19:11
Hi all, I'll get to this today, thanks! Sorry for the delay.

**Comment by amiantos** [comment] 2023-01-05 19:36
Dupe of https://github.com/amiantos/pibar/issues/46

I'll get a release in that issue for testing today.

**Closed by amiantos** 2023-01-05 19:36 UTC
