### ISSUE TITLE
PiBar broken after recent Pihole Update

### ISSUE THREAD

**Issue by CryptoKnight360** [amiantos/pibar#48] opened 2022-12-31 00:53 UTC
Hello. I have PiBar purchased through the Mac App Store and the app has been broken for a bit now. Pihole recently had a big update to their API and FTL and it broke PiBar functionality. Please update.  :)

**Comment by RyanMulready** [comment] 2023-01-03 15:04
👍 PiBar is always showing my piholes offline now even though they aren't. Removed and readded config/API keys with no luck.

**Comment by CryptoKnight360** [comment] 2023-01-03 20:23
Yeah, so much for “Buy from the App Store to support and Updates”. I think this dude completely abandoned this project and yet it’s still on the App store.

**Comment by amiantos** [comment] 2023-01-05 19:12
> Yeah, so much for “Buy from the App Store to support and Updates”. I think this dude completely abandoned this project and yet it’s still on the App store. 

I replied in another issue that I've been on vacation this week and I have been moving. Sorry for the delay.

**Comment by amiantos** [comment] 2023-01-05 19:36
Dupe of https://github.com/amiantos/pibar/issues/46

I'll get a release in that issue for testing today.

**Closed by amiantos** 2023-01-05 19:36 UTC

**Comment by amiantos** [comment] 2023-01-05 20:09
@CryptoKnight360 if you are reviewer "Majesty1418" on the App Store, I would appreciate it if you would remove or update your negative review. Thanks.

![image](https://user-images.githubusercontent.com/1126616/210870785-b90fc345-b9e5-4d6a-a380-1b49dd41387d.png)
