### ISSUE TITLE
Pibar doesn´t work after the last update of Pihole

### ISSUE THREAD

**Issue by Duoaccess** [amiantos/pibar#52] opened 2023-01-21 10:11 UTC
Hello,
since my last update of pihole in the last week, pibar doesn´t work anymore again. There must have been a further change in pihole. Colud you please check this. Testing it, pibar can´t get a connection to the pihole. No settings have been changed by me. Thank you very much!

**Comment by GPSPython** [comment] 2023-01-22 12:07
I've had the same problem, updating manually to v1.1.2 from github resolved the issue for me.

**Comment by amiantos** [comment] 2023-01-23 17:55
Duplicate of https://github.com/amiantos/pibar/issues/46

Please get the latest update from the App Store or grab 1.1.2 from here: https://github.com/amiantos/pibar/releases/tag/macOS-v1.1.2

**Closed by amiantos** 2023-01-23 17:55 UTC
